// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.jsx";
import * as $1 from "./routes/_layout.jsx";
import * as $2 from "./routes/_middleware.js";
import * as $3 from "./routes/collection/[collection].jsx";
import * as $4 from "./routes/game/[game].jsx";
import * as $5 from "./routes/game/_middleware.js";
import * as $6 from "./routes/gamepass/[collection].jsx";
import * as $7 from "./routes/gold/[collection].jsx";
import * as $8 from "./routes/index.jsx";
import * as $9 from "./routes/news.jsx";
import * as $10 from "./routes/search.jsx";
import * as $11 from "./routes/wishlist.jsx";
import * as $$0 from "./islands/CollectionList.jsx";
import * as $$1 from "./islands/GameListIsland.jsx";
import * as $$2 from "./islands/MarketplaceIsland.jsx";
import * as $$3 from "./islands/PageTransition.jsx";
import * as $$4 from "./islands/ShareButton.jsx";
import * as $$5 from "./islands/Video.jsx";
import * as $$6 from "./islands/VideoPlaylist.jsx";
import * as $$7 from "./islands/WishToggle.jsx";
import * as $$8 from "./islands/Wishlist.jsx";

const manifest = {
  routes: {
    "./routes/_app.jsx": $0,
    "./routes/_layout.jsx": $1,
    "./routes/_middleware.js": $2,
    "./routes/collection/[collection].jsx": $3,
    "./routes/game/[game].jsx": $4,
    "./routes/game/_middleware.js": $5,
    "./routes/gamepass/[collection].jsx": $6,
    "./routes/gold/[collection].jsx": $7,
    "./routes/index.jsx": $8,
    "./routes/news.jsx": $9,
    "./routes/search.jsx": $10,
    "./routes/wishlist.jsx": $11,
  },
  islands: {
    "./islands/CollectionList.jsx": $$0,
    "./islands/GameListIsland.jsx": $$1,
    "./islands/MarketplaceIsland.jsx": $$2,
    "./islands/PageTransition.jsx": $$3,
    "./islands/ShareButton.jsx": $$4,
    "./islands/Video.jsx": $$5,
    "./islands/VideoPlaylist.jsx": $$6,
    "./islands/WishToggle.jsx": $$7,
    "./islands/Wishlist.jsx": $$8,
  },
  baseUrl: import.meta.url,
};

export default manifest;
